//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WytSkyDelivery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WytSkyDelivery.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        public static string Msg_CloseApp {
            get {
                return ResourceManager.GetString("Msg_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you shoud communicate with the maniger in order to activate your account on this device .
        /// </summary>
        public static string Msg_ConectToAdminForRegesterUser {
            get {
                return ResourceManager.GetString("Msg_ConectToAdminForRegesterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection , Make sure that Wi-Fi or mobile data is turned on , then try again.
        /// </summary>
        public static string Msg_ConnectionError {
            get {
                return ResourceManager.GetString("Msg_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: An error has occurred, try again.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection , Make sure that Wi-Fi or mobile data is turned on , then try again.
        /// </summary>
        public static string Msg_NoInternetConnection {
            get {
                return ResourceManager.GetString("Msg_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: you entered an incorrect email.
        /// </summary>
        public static string Msg_NotValidEmail {
            get {
                return ResourceManager.GetString("Msg_NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Code.
        /// </summary>
        public static string Msg_NotValidOrgCode {
            get {
                return ResourceManager.GetString("Msg_NotValidOrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect Password.
        /// </summary>
        public static string Msg_NotValidPassword {
            get {
                return ResourceManager.GetString("Msg_NotValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry : you entered an incorrect UserName.
        /// </summary>
        public static string Msg_NotValidUserName {
            get {
                return ResourceManager.GetString("Msg_NotValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite one of your friends and get
        ///30 riyals free when subscribing.
        /// </summary>
        public static string Msg_SheareAppFriend {
            get {
                return ResourceManager.GetString("Msg_SheareAppFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation accomplished successfully.
        /// </summary>
        public static string Msg_Success {
            get {
                return ResourceManager.GetString("Msg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry: the time limit has expired. Please log in again.
        /// </summary>
        public static string Msg_TimeExpired {
            get {
                return ResourceManager.GetString("Msg_TimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code that you received on the e-mail.
        /// </summary>
        public static string Msg_VerficationCode {
            get {
                return ResourceManager.GetString("Msg_VerficationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Test_Address {
            get {
                return ResourceManager.GetString("Test_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiztion Code.
        /// </summary>
        public static string Test_OrganiztionCode {
            get {
                return ResourceManager.GetString("Test_OrganiztionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Text_AboutUs {
            get {
                return ResourceManager.GetString("Text_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Text_Approve {
            get {
                return ResourceManager.GetString("Text_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Text_Cancle {
            get {
                return ResourceManager.GetString("Text_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Company.
        /// </summary>
        public static string Text_ChangeCompany {
            get {
                return ResourceManager.GetString("Text_ChangeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Text_ChangePassword {
            get {
                return ResourceManager.GetString("Text_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Text_Client {
            get {
                return ResourceManager.GetString("Text_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close alurt.
        /// </summary>
        public static string Text_CloseApp {
            get {
                return ResourceManager.GetString("Text_CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        public static string Text_CompanyCode {
            get {
                return ResourceManager.GetString("Text_CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details ....
        /// </summary>
        public static string Text_Details {
            get {
                return ResourceManager.GetString("Text_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Text_Details_ {
            get {
                return ResourceManager.GetString("Text_Details_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_Email {
            get {
                return ResourceManager.GetString("Text_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email / Phone.
        /// </summary>
        public static string Text_EmailOrPhone {
            get {
                return ResourceManager.GetString("Text_EmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Text_Enter {
            get {
                return ResourceManager.GetString("Text_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Text_Error {
            get {
                return ResourceManager.GetString("Text_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Text_Home {
            get {
                return ResourceManager.GetString("Text_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Text_Language {
            get {
                return ResourceManager.GetString("Text_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Details ....
        /// </summary>
        public static string Text_LessDetails {
            get {
                return ResourceManager.GetString("Text_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Text_Loading {
            get {
                return ResourceManager.GetString("Text_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Text_Login {
            get {
                return ResourceManager.GetString("Text_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Text_LogOut {
            get {
                return ResourceManager.GetString("Text_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message ....
        /// </summary>
        public static string Text_Message {
            get {
                return ResourceManager.GetString("Text_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alurt.
        /// </summary>
        public static string Text_Message_ {
            get {
                return ResourceManager.GetString("Text_Message_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details ....
        /// </summary>
        public static string Text_MoreDetails {
            get {
                return ResourceManager.GetString("Text_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Text_Notes {
            get {
                return ResourceManager.GetString("Text_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Text_OldPassword {
            get {
                return ResourceManager.GetString("Text_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location.
        /// </summary>
        public static string Text_OpenLocation {
            get {
                return ResourceManager.GetString("Text_OpenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Code.
        /// </summary>
        public static string Text_OrderCode {
            get {
                return ResourceManager.GetString("Text_OrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string Text_OrderDetails {
            get {
                return ResourceManager.GetString("Text_OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string Text_OrderId {
            get {
                return ResourceManager.GetString("Text_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Text_Orders {
            get {
                return ResourceManager.GetString("Text_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string Text_PersonalData {
            get {
                return ResourceManager.GetString("Text_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Text_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Text_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Text_Profile {
            get {
                return ResourceManager.GetString("Text_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code Scan.
        /// </summary>
        public static string Text_QRCodeScan {
            get {
                return ResourceManager.GetString("Text_QRCodeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        public static string Text_RateApp {
            get {
                return ResourceManager.GetString("Text_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Text_Register {
            get {
                return ResourceManager.GetString("Text_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        public static string Text_ScanQR {
            get {
                return ResourceManager.GetString("Text_ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Text_Send {
            get {
                return ResourceManager.GetString("Text_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share App.
        /// </summary>
        public static string Text_ShareApp {
            get {
                return ResourceManager.GetString("Text_ShareApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Text_SignIn {
            get {
                return ResourceManager.GetString("Text_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Text_SignUp {
            get {
                return ResourceManager.GetString("Text_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Text_Skip {
            get {
                return ResourceManager.GetString("Text_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string Text_TryAgain {
            get {
                return ResourceManager.GetString("Text_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delevired.
        /// </summary>
        public static string Text_updateOrderDetails {
            get {
                return ResourceManager.GetString("Text_updateOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Text_Use {
            get {
                return ResourceManager.GetString("Text_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Text_Welcome {
            get {
                return ResourceManager.GetString("Text_Welcome", resourceCulture);
            }
        }
    }
}
